"""empty message

Revision ID: 9f9ed1b118a3
Revises: 415a2c009eb0
Create Date: 2023-01-26 19:24:28.138650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9ed1b118a3'
down_revision = '415a2c009eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vehiculos_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('altura',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('poblacion',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('terreno',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('constraseña',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('mail',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('capacidad',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('creacion',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('creacion',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('capacidad',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('mail',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('constraseña',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('terreno',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('poblacion',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.alter_column('altura',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vehiculos_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
