"""empty message

Revision ID: f2ce1ecb1cbc
Revises: dd604d1ac492
Create Date: 2023-01-26 14:54:25.748630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ce1ecb1cbc'
down_revision = 'dd604d1ac492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agregar', sa.String(length=250), nullable=False),
    sa.Column('eliminar', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    # ### end Alembic commands ###
