"""empty message

Revision ID: fe13533b1280
Revises: 9f9ed1b118a3
Create Date: 2023-01-30 15:48:03.451625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe13533b1280'
down_revision = '9f9ed1b118a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.String(length=20), nullable=True))
        batch_op.drop_column('constraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('constraseña', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###
